name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Github release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}